name: build image

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: echo "Build flask docker image"

      - uses: docker-practice/actions-setup-docker@master

      - name: Build image
        run: docker build -t app:latest .